### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by alex-malyita** [rustavellyne/CV#1]
- [x] Придерживайся прорядка правил в CS. Например - body, h1, a, ul, header, content, footer

- [x] 4 пробела в качестве таба (Отступ перед свойством правила)

- [x] [style](https://github.com/rustavellyne/CV/blob/master/cv/styles.css#L57) много непонятные пустых мест. Делай код читабельным !

**Comment by rustavellyne** [comment]
4 пробела в качестве таба (Отступ перед свойством правила)

это Гитхаб мне исправляет, я выставляю 4, а при заливе на гит там 8 пробелов ставится, в настройках гитхаба менял на 4, но все равно ставит 8
